// <auto-generated />
using System;
using GestaoCulto.Repository.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoCulto.Repository.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20240607115038_Add_20240607")]
    partial class Add_20240607
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestaoCulto.Domain.Models.CongregacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Status")
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.ToTable("congregacao");
                });

            modelBuilder.Entity("GestaoCulto.Domain.Models.ParametrosSistemaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CongregacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Status")
                        .HasColumnType("char(1)");

                    b.Property<string>("Valor")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CongregacaoId");

                    b.ToTable("parametros_sistema");
                });

            modelBuilder.Entity("GestaoCulto.Domain.Models.PessoasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CongregacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("FoneCelular")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Status")
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("CongregacaoId");

                    b.ToTable("pessoas");
                });

            modelBuilder.Entity("GestaoCulto.Domain.Models.UsuariosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CongregacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Senha")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("CongregacaoId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("GestaoCulto.Domain.Models.ParametrosSistemaModel", b =>
                {
                    b.HasOne("GestaoCulto.Domain.Models.CongregacaoModel", "Congregacao")
                        .WithMany("ParametrosSistemas")
                        .HasForeignKey("CongregacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoCulto.Domain.Models.PessoasModel", b =>
                {
                    b.HasOne("GestaoCulto.Domain.Models.CongregacaoModel", "Congregacao")
                        .WithMany()
                        .HasForeignKey("CongregacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoCulto.Domain.Models.UsuariosModel", b =>
                {
                    b.HasOne("GestaoCulto.Domain.Models.CongregacaoModel", "Congregacao")
                        .WithMany("UsuariosSistemas")
                        .HasForeignKey("CongregacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
